name: matrix_project
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  matrix: ^0.31.0
  flutter_olm: ^2.0.0
  flutter_openssl_crypto: ^0.5.0
  gap: ^3.0.1
  mockito: ^5.4.4
  dartx: ^1.2.0
  dartz: ^0.10.1
  flash: ^3.1.1
  flutter_secure_storage: ^9.2.2
  hooks_riverpod: ^2.5.1
  dio_cookie_manager: ^3.1.1
  equatable: ^2.0.5
  page_transition: ^2.1.0
  logger: ^2.4.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  synchronized: ^3.1.0+1
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^6.0.4
  internet_connection_checker_plus: ^2.5.1
  modal_bottom_sheet: ^3.0.0
  cached_network_image: ^3.4.0
  intersperse: ^2.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
